settings:
  title: 'ç½‘ç«™è¿è¡Œç›‘æ§'
  url: 'https://amzm.121723.xyz' # used for Slack messages, è¿™ä¸ªä¸ç¡®å®šæ˜¯ä»€ä¹ˆç”¨
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 99 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: 'æ‰€æœ‰ç½‘ç«™è¿è¡Œæ­£å¸¸'
  notAllmonitorsOperational: 'éƒ¨åˆ†ç½‘ç«™å‡ºç°é—®é¢˜, é•¿æ—¶é—´æœªæ¢å¤è¯·è”ç³»ğŸ“§s@znhy.uk, é˜¿é‡Œå˜å¤šğŸ«¡'
  monitorLabelOperational: 'è¿è¡Œæ­£å¸¸'
  monitorLabelNotOperational: 'è¿è¡Œå¼‚å¸¸'
  monitorLabelNoData: 'æš‚æ— æ•°æ®'
  dayInHistogramNoData: 'æš‚æ— æ•°æ®'
  dayInHistogramOperational: 'ä¸€åˆ‡æ­£å¸¸'
  dayInHistogramNotOperational: ' äº‹ä»¶' # xx incident(s) recorded

monitors:

  - id: synctv # unique identifier
    name: ğŸ‘«ä¸€ä¸ªå¯ä»¥è¿œç¨‹ä¸€èµ·çœ‹ç”µå½±/ç›´æ’­çš„ç¨‹åºğŸ¿
    description: 'ä¸€èµ·çœ‹å‰§å§ //serv00' # default=emptyÂ Â 
    url: 'https://sync.121723.xyz/web/'

  - id: alist00 # unique identifier
    name: å’–å•¡å±‹å¤‡ç”¨ç«™
    description: 'éƒ¨ç½²çš„alistæœåŠ¡ï¼Œé›†æˆäº†åŒ¿åèŠå¤©å®¤å’Œä¸€èµ·çœ‹åŠŸèƒ½ //serv00' # default=empty
    url: 'https://p00.121723.xyz/'

  - id: newapi # unique identifier
    name: New API
    description: 'éƒ¨ç½²çš„New Api //serv00' # default=emptyÂ Â Â Â 
    url: 'https://zf.121723.xyz/'

#  - id: bing03 # unique identifier
#    name: ç½‘é¡µnew bing
#    description: 'éƒ¨ç½²åœ¨åæ²™ç½‘é¡µnew bing, å›½å†…å¯è®¿é—® //serv07' # default=empty
#    url: 'https://b7.121723.xyz/web/'
    
  - id: reader # unique identifier
    name: ğŸ“–ğŸ“•ğŸ“—ğŸ“˜ğŸ“™ğŸ“š
    description: 'åœ¨çº¿é˜…è¯»å™¨ //serv07' # default=empty
    url: 'https://reader.121723.xyz/login?next=%2F'

  - id: lx-sync # unique identifier
    name: ğŸ¥³ğŸ§ğŸµ
    description: 'lx-musicçš„æ•°æ®åŒæ­¥æœåŠ¡ //serv07' # default=empty
    url: 'https://lx.121723.xyz/hello'

  - id: pico # unique identifierÂ 
    name: ğŸª„ğŸ›«picoshareğŸ›¬
    description: 'æ–‡ä»¶åˆ†äº«æœåŠ¡ //serv08' # default=emptyÂ 
    url: 'https://pico.121723.xyz/'

  - id: memos # unique identifierÂ 
    name: âœï¸Memos
    description: 'Memos, å¯ä»¥å½“æˆå¤‡å¿˜å½• //serv0ï¸âƒ£8ï¸âƒ£' # default=emptyÂ Â 
    url: 'https://memos.121723.xyz/'

#  - id: bing-self # unique identifier
#    name: ç½‘é¡µnew bing 
#    description: 'éƒ¨ç½²åœ¨cfçš„ç½‘é¡µnew bingï¼Œ å›½å†…å¯è®¿é—®' # default=emptyÂ 
#    url: 'https://bing.121723.xyz/web/'

  - id: blog # unique identifier
    name: my blog
    description: 'éƒ¨ç½²åœ¨å¤§å–„äººCFå®¶workersçš„ä¸ªäººåšå®¢' # default=empty
    url: 'https://blog.121723.xyz/'

  - id: znhy-email # unique identifier
    name: ğŸ“®ğŸ“®ğŸ“®æ— é™é‚®ç®±
    description: 'Infinite Email' # default=emptyÂ Â 
    url: 'https://mail.znhy.uk/'
    expectStatus: 302

  - id: alist # unique identifier
    name: çˆ±ä¸½ä¸çš„å’–å•¡å±‹
    description: 'è‡ªéƒ¨ç½²çš„alistæœåŠ¡ï¼Œé›†æˆäº†åŒ¿åèŠå¤©å®¤å’Œä¸€èµ·çœ‹åŠŸèƒ½' # default=empty
    url: 'https://pan.121723.xyz/'

  - id: notify # unique identifierÂ Â 
    name: notify
    description: 'éƒ¨ç½²çš„notifyæœåŠ¡' # default=emptyÂ Â 
    url: 'https://ntfy.121723.xyz/'

  - id: vault # unique identifierÂ Â Â 
    name: vaultwarden
    description: 'vaultwarden' # default=emptyÂ Â 
    url: 'https://vault.znhy.uk/'

  - id: ddg # unique identifier
    name: ğŸ“®ğŸ“®ğŸ“§duckduckgoé¢æ¿
    description: 'ddgé¢æ¿' # default=empty
    url: 'https://ddg.znhy.uk/zh-CN/email'

  - id: ddg1 # unique identifier
    name: ğŸ“®ğŸ“®ğŸ“§duckduckgoé¢æ¿
    description: 'ddgé¢æ¿' # default=emptyÂ 
    url: 'https://ddg.121723.xyz/zh-CN/email'
    
  - id: photogragh # unique identifier
    name: ğŸŒ…ğŸŒ†ğŸŒŒä¸ªäººæ‘„å½±å±•
    description: 'ä¸ªäººæ‘„å½±ä½œå“å±•ç¤ºç«™' # default=emptyÂ 
    url: 'https://photo.znhy.uk'

  - id: pastebin # unique identifier
    name: ğŸ—’ï¸ğŸ“‹ğŸ“è‡ªç”¨äº‘å‰ªåˆ‡æ¿
    description: 'éƒ¨ç½²åœ¨cfçš„pastebin' # default=emptyÂ 
    url: 'https://note.slzr.us.kg'

  
#  - id: home # unique identifierÂ 
#    name: ğŸ 
#    description: 'æ­¤ç›‘æ§å’Œå¯¼èˆªé¡µé¢' # default=empty
#    url: 'https://amzm.121723.xyz/'

#  - id: sd # unique identifierÂ 
#    name: stable diffusion
#    description: 'åˆæ˜¯å¤§å–„äººæä¾›çš„æœåŠ¡ï¼Œç›®å‰åªè¿”å›ä¸ªç‹—å¤´' # default=empty
#    url: 'https://sd.121723.xyz/'

#  - id: llm # unique identifierÂ 
#    name: large language model
#    description: 'CFå¤§å–„äººå•Š' # default=empty
#    url: 'https://llm.121723.xyz/'

#  - id: workers-cloudflare-com # unique identifier
#    name: workers.cloudflare.com
#   description: 'You write code. They handle the rest.' # default=empty
#   url: 'https://workers.cloudflare.com/' # URL to fetch
#    method: GET # default=GET
#    expectStatus: 200 # operational status, default=200Â 
#    followRedirect: false # should fetch follow redirects, default=falseÂ 
#    linkable: false # allows the title to be a link, default=true

#  - id: www-cloudflare-com
#    name: www.cloudflare.com
#    description: 'Built for anything connected to the Internet.'
#    url: 'https://www.cloudflare.com'
#    method: GET
#    expectStatus: 200
#    linkable: true # allows the title to be a link, default=true

#  - id: blog-cloudflare-com
#    name: The Cloudflare Blog
#    url: 'https://blog.cloudflare.com/'
#    method: GET
#    expectStatus: 200
