settings:
  title: 'ç½‘ç«™è¿è¡Œç›‘æ§'
  url: 'https://amzm.121723.xyz' # used for Slack messages, è¿™ä¸ªä¸ç¡®å®šæ˜¯ä»€ä¹ˆç”¨
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 99 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'æ‰€æœ‰ç½‘ç«™è¿è¡Œæ­£å¸¸'
  notAllmonitorsOperational: 'éƒ¨åˆ†ç½‘ç«™å‡ºç°é—®é¢˜'
  monitorLabelOperational: 'è¿è¡Œæ­£å¸¸'
  monitorLabelNotOperational: 'è¿è¡Œå¼‚å¸¸'
  monitorLabelNoData: 'æš‚æ— æ•°æ®'
  dayInHistogramNoData: 'æš‚æ— æ•°æ®'
  dayInHistogramOperational: 'ä¸€åˆ‡æ­£å¸¸'
  dayInHistogramNotOperational: ' äº‹ä»¶' # xx incident(s) recorded

monitors:
  - id: bing01 # unique identifier
    name: ç½‘é¡µnew bingâ‘ 
    description: 'ç½‘å‹åˆ†äº«çš„ç½‘é¡µnew bingï¼Œ å›½å†…å¯è®¿é—®' # default=empty
    url: 'https://bingai.zklcdc.xyz/'
    expectStatus: 403
    followRedirect: true



  - id: bing02 # unique identifier
    name: ç½‘é¡µnew bingâ‘¡
    description: 'ç½‘å‹åˆ†äº«çš„ç½‘é¡µnew bingï¼Œ å›½å†…å¯è®¿é—®' # default=empty
    url: 'https://bingface.b1ghawk.xyz/'


  - id: bing03 # unique identifier
    name: ç½‘é¡µnew bingâ‘¢
    description: 'åæ²™ç½‘é¡µnew bingï¼Œ å›½å†…å¯è®¿é—®' # default=empty
    url: 'https://b7.121723.xyz/web/index.html'
    
  - id: bing-self # unique identifier
    name: ç½‘é¡µnew bingâ‘£
    description: 'ç½‘é¡µnew bingï¼Œ å›½å†…å¯è®¿é—®' # default=empty
    url: 'https://bing.121723.xyz/web/'

  - id: alist # unique identifier
    name: çˆ±ä¸½ä¸çš„å’–å•¡å±‹
    description: 'éƒ¨ç½²çš„alistæœåŠ¡ï¼Œé›†æˆäº†åŒ¿åèŠå¤©å®¤å’Œä¸€èµ·çœ‹åŠŸèƒ½' # default=empty
    url: 'https://pan.121723.xyz/'

  - id: blog # unique identifier
    name: çˆ±ä¸½ä¸çš„åšå®¢
    description: 'éƒ¨ç½²åœ¨å¤§å–„äººCFå®¶workersçš„ä¸ªäººåšå®¢' # default=empty
    url: 'https://blog.121723.xyz/'
    
  - id: notify # unique identifier
    name: notify
    description: 'éƒ¨ç½²çš„notifyæœåŠ¡' # default=empty
    url: 'https://ntfy.121723.xyz/'

#  - id: reader # unique identifier
#    name: åœ¨çº¿é˜…è¯»å™¨
#    description: 'è®¡åˆ’éƒ¨ç½²' # default=empty
#    url: 'https://reader.121723.xyz/home'
#    linkable: false
  
#  - id: home # unique identifier
#    name: ğŸ 
#    description: 'æ­¤ç›‘æ§å’Œå¯¼èˆªé¡µé¢' # default=empty
#    url: 'https://amzm.121723.xyz/'

#  - id: sd # unique identifier
#    name: stable diffusion
#    description: 'åˆæ˜¯å¤§å–„äººæä¾›çš„æœåŠ¡ï¼Œç›®å‰åªè¿”å›ä¸ªç‹—å¤´' # default=empty
#    url: 'https://sd.121723.xyz/'

#  - id: llm # unique identifier
#    name: large language model
#    description: 'CFå¤§å–„äººå•Š' # default=empty
#    url: 'https://llm.121723.xyz/'

  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
